// App Registry — add new apps here
export interface AppConfig {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
  gradient: string;
  roles?: string[]; // If set, only these roles can see the app. If unset, all roles can see it.
}

export const APPS: AppConfig[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: '📊',
    description: 'Tổng quan cho CEO',
    color: '#8B5CF6',
    gradient: 'linear-gradient(135deg, #8B5CF6 0%, #6366F1 100%)',
    roles: ['admin', 'ke_toan'],
  },
  {
    id: 'invoice',
    name: 'Invoice',
    icon: '📄',
    description: 'Quản lý hoá đơn & doanh thu',
    color: '#FF9500',
    gradient: 'linear-gradient(135deg, #FF9500 0%, #FF5E3A 100%)',
    roles: ['admin', 'ke_toan'],
  },
  {
    id: 'expense',
    name: 'Expense',
    icon: '💰',
    description: 'Quản lý chi phí & thanh toán',
    color: '#34C759',
    gradient: 'linear-gradient(135deg, #34C759 0%, #30D158 100%)',
    roles: ['admin', 'ke_toan'],
  },
  {
    id: 'workforce',
    name: 'Workforce',
    icon: '👷',
    description: 'Quản lý Task và nghiệm thu',
    color: '#5856D6',
    gradient: 'linear-gradient(135deg, #5856D6 0%, #AF52DE 100%)',
    roles: ['admin', 'ke_toan'],
  },
  {
    id: 'crm',
    name: 'CRM',
    icon: '👥',
    description: 'Quản lý khách hàng tập trung',
    color: '#0A84FF',
    gradient: 'linear-gradient(135deg, #0A84FF 0%, #5E5CE6 100%)',
    roles: ['admin', 'ke_toan', 'bd'],
  },
  {
    id: 'hr',
    name: 'HR',
    icon: '🧑‍💼',
    description: 'Quản lý nhân sự toàn diện',
    color: '#FF375F',
    gradient: 'linear-gradient(135deg, #FF375F 0%, #FF6B81 100%)',
    roles: ['admin', 'hr', 'ke_toan'],
  },
  {
    id: 'attendance',
    name: 'Chấm công',
    icon: '⏰',
    description: 'Chấm công & quản lý ca làm việc',
    color: '#FF6B35',
    gradient: 'linear-gradient(135deg, #FF6B35 0%, #F7C948 100%)',
    roles: ['admin', 'hr', 'ke_toan'],
  },
  {
    id: 'payroll',
    name: 'Tính lương',
    icon: '💵',
    description: 'Tính lương & thuế TNCN',
    color: '#10B981',
    gradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    roles: ['admin', 'ke_toan', 'hr'],
  },
  {
    id: 'portal',
    name: 'Employee Portal',
    icon: '🏠',
    description: 'Thông tin cá nhân & bảng lương',
    color: '#06B6D4',
    gradient: 'linear-gradient(135deg, #06B6D4 0%, #0891B2 100%)',
    roles: ['member', 'bd'],
  },
  {
    id: 'freelancer-portal',
    name: 'Freelancer Portal',
    icon: '🎨',
    description: 'Tasks, nghiệm thu & thu nhập',
    color: '#F59E0B',
    gradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
    roles: ['freelancer'],
  },
  {
    id: 'accounting',
    name: 'Kế toán',
    icon: '🧾',
    description: 'Tài sản cố định & tạm ứng',
    color: '#6366F1',
    gradient: 'linear-gradient(135deg, #6366F1 0%, #4F46E5 100%)',
    roles: ['admin', 'ke_toan'],
  },
  {
    id: 'company',
    name: 'Công ty',
    icon: '🏢',
    description: 'Hồ sơ pháp lý & giấy tờ',
    color: '#64748B',
    gradient: 'linear-gradient(135deg, #64748B 0%, #475569 100%)',
    roles: ['admin', 'ke_toan', 'hr'],
  },
  {
    id: 'ai-agent',
    name: 'AI Agent',
    icon: '🤖',
    description: 'Hệ thống AI Agent cho TDGames',
    color: '#8B5CF6',
    gradient: 'linear-gradient(135deg, #8B5CF6 0%, #A855F7 100%)',
    roles: ['admin'],
  },
  {
    id: 'system-monitor',
    name: 'System Monitor',
    icon: '📡',
    description: 'Giám sát uptime & sức khoẻ hệ thống',
    color: '#06B6D4',
    gradient: 'linear-gradient(135deg, #06B6D4 0%, #0284C7 100%)',
    roles: ['admin'],
  },
  {
    id: 'handbook',
    name: 'Company Hub',
    icon: '🏢',
    description: 'Nội quy, chính sách & tài liệu nội bộ',
    color: '#22C55E',
    gradient: 'linear-gradient(135deg, #22C55E 0%, #16A34A 100%)',
    roles: ['member', 'bd'],
  },
];
